#!/usr/bin/env node
// Build the offline PWA into docs/ (served by GitHub Pages).
//
//   node build.js
//
// docs/ = public/ + the local-storage adapter swapped in as store.js, PWA head
// tags injected, seed cards baked from the live data file, and a service
// worker whose cache name is a content hash of everything it precaches.
// Deterministic: same inputs, same output.

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = __dirname;
const PUBLIC = path.join(ROOT, 'public');
const PWA = path.join(ROOT, 'pwa');
const DOCS = path.join(ROOT, 'docs');
const DATA = path.join(ROOT, 'flashdesk-data.json');

const PRESERVE = new Set(['screenshot.jpg', 'superpowers']); // docs/ history that predates the site
const MARKER = '<!-- build:pwa -->';

function fail(msg) {
  console.error(`build failed: ${msg}`);
  process.exit(1);
}

// 1. Guard: the injection marker must exist before we touch anything.
const indexSrc = fs.readFileSync(path.join(PUBLIC, 'index.html'), 'utf8');
if (!indexSrc.includes(MARKER)) fail(`missing "${MARKER}" marker in public/index.html`);

// 2. Clean docs/ except the preserve-list.
fs.mkdirSync(DOCS, { recursive: true });
for (const entry of fs.readdirSync(DOCS)) {
  if (PRESERVE.has(entry)) continue;
  fs.rmSync(path.join(DOCS, entry), { recursive: true, force: true });
}

// 3. Copy public/ -> docs/ (index.html, app.js, styles.css, store.js, fonts/).
fs.cpSync(PUBLIC, DOCS, { recursive: true });

// 4. The PWA uses the local-storage adapter as its store.js.
fs.copyFileSync(path.join(PWA, 'store-local.js'), path.join(DOCS, 'store.js'));

// 5. Inject the PWA head tags at the marker.
const headSnippet = fs.readFileSync(path.join(PWA, 'head-snippet.html'), 'utf8').trimEnd();
fs.writeFileSync(path.join(DOCS, 'index.html'), indexSrc.replace(MARKER, headSnippet));

// 6. Bake seed cards (front/back/deck only — review state stays on each device).
let seedCards;
let seedSource;
try {
  const data = JSON.parse(fs.readFileSync(DATA, 'utf8'));
  seedCards = data.cards.map(({ front, back, deck }) => ({ front, back, deck }));
  seedSource = 'flashdesk-data.json';
} catch {
  seedCards = require('./seed.js').map(({ front, back, deck }) => ({ front, back, deck }));
  seedSource = 'seed.js (flashdesk-data.json not readable — is this a fresh clone?)';
  console.warn(`warning: seeding from ${seedSource}`);
}
fs.writeFileSync(
  path.join(DOCS, 'seed-data.js'),
  `// Generated by build.js — the deck this PWA starts with on a new device.\n`
  + `window.FLASHDESK_SEED = ${JSON.stringify(seedCards, null, 2)};\n`
);

// 7. Manifest + icons.
fs.copyFileSync(path.join(PWA, 'manifest.webmanifest'), path.join(DOCS, 'manifest.webmanifest'));
for (const png of ['icon-180.png', 'icon-192.png', 'icon-512.png']) {
  fs.copyFileSync(path.join(PWA, 'icons', png), path.join(DOCS, png));
}

// 8. Service worker last: cache name = hash of every deployed file's bytes,
// so any content change produces a new cache and a clean update.
function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = path.join(dir, e.name);
    return e.isDirectory() ? walk(p) : [p];
  });
}
const deployed = walk(DOCS)
  .filter((p) => !PRESERVE.has(path.relative(DOCS, p).split(path.sep)[0]))
  .filter((p) => path.basename(p) !== 'sw.js')
  .sort();
const hash = crypto.createHash('sha1');
for (const p of deployed) hash.update(path.relative(DOCS, p)).update(fs.readFileSync(p));
const version = hash.digest('hex').slice(0, 10);

const sw = fs.readFileSync(path.join(PWA, 'sw.js'), 'utf8');
if (!sw.includes('__CACHE_VERSION__')) fail('missing __CACHE_VERSION__ placeholder in pwa/sw.js');
fs.writeFileSync(path.join(DOCS, 'sw.js'), sw.replace('__CACHE_VERSION__', version));

// 9. No Jekyll processing on Pages.
fs.writeFileSync(path.join(DOCS, '.nojekyll'), '');

console.log(`built docs/: ${deployed.length + 1} files, ${seedCards.length} seed cards (from ${seedSource}), cache flashdesk-${version}`);
